# Generated by Django 4.1.4 on 2022-12-31 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_payment_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterModelOptions(
            name="paymentinstance",
            options={"ordering": ("-start_date",)},
        ),
        migrations.RenameField(
            model_name="paymentinstance",
            old_name="payer",
            new_name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
