# Generated by Django 4.1.4 on 2023-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_payment_amount_alter_payment_recipient_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinstance",
            name="recipient_has_account",
        ),
        migrations.AlterField(
            model_name="paymentinstance",
            name="recipient_stripe_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
