# Generated by Django 4.1.4 on 2023-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_paymentinstance_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
