# Generated by Django 4.1.4 on 2023-01-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0008_rename_stripe_payement_method_id_paymentmethod_stripe_payment_method_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinstance",
            name="task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
