# Generated by Django 4.1.4 on 2023-01-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_paymentinstance_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinstance",
            name="task_id",
        ),
    ]
