# Generated by Django 4.1.4 on 2023-01-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_paymentinstance_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="recpiient_stripe_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
