# Generated by Django 4.1.4 on 2023-01-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_payment_recpiient_stripe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="recpiient_stripe_id",
        ),
    ]
