# Generated by Django 4.1.4 on 2023-01-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_paymentmethod_stripe_payment_method_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="stripe_account_id",
        ),
    ]
