# Generated by Django 4.1.4 on 2023-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_paymentmethod_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
